TENSORFLOW

Import libraries

In [1]:
import tensorflow as tf
import numpy as np

In [2]:
a = tf.constant(15)
b = tf.constant(20)
print(a + b)

tf.Tensor(35, shape=(), dtype=int32)


Input

In [3]:
x = np.random.rand(100).astype(np.float32)
print(x)

[0.32089117 0.48678783 0.6469571  0.6110041  0.25395954 0.5966876
 0.01928315 0.09073218 0.5644797  0.47326565 0.1362917  0.34838668
 0.24158578 0.4803574  0.20483519 0.4766558  0.445309   0.2975506
 0.7287576  0.74548686 0.25168034 0.62823844 0.8382431  0.37201262
 0.53377175 0.9779963  0.61823434 0.1504635  0.43870085 0.25643408
 0.03768029 0.45891097 0.9817892  0.2770029  0.01937499 0.6238944
 0.8851388  0.5441238  0.9127868  0.0956918  0.0933931  0.6448871
 0.536059   0.10341199 0.5749123  0.86007154 0.46477005 0.4567407
 0.5532915  0.47226393 0.54642075 0.26406193 0.03336901 0.40313473
 0.8026953  0.7882445  0.86143595 0.8159964  0.45536926 0.89320123
 0.5860312  0.659665   0.79904234 0.24897754 0.7541307  0.4259298
 0.54640585 0.633725   0.10508041 0.36598626 0.3167717  0.1643219
 0.13702899 0.5604054  0.29818997 0.6667291  0.92617494 0.66796565
 0.36141008 0.6537881  0.33839288 0.20880798 0.9652689  0.1742207
 0.11011086 0.999921   0.42805552 0.30013832 0.94421595 0.23895794
 0.

Output

In [4]:
y = x * 0.2 + 0.2

Weight

In [5]:
w = tf.Variable(tf.random.normal([1]))

Bias

In [6]:
b = tf.Variable(tf.zeros([1]))

Create a function for MSE - Mean Squared Error

In [7]:
def mse_loss():
  ypred = w * x + b
  loss = tf.reduce_mean(tf.square(ypred - y))
  return loss

Optimizer

In [8]:
optimizer = tf.keras.optimizers.Adam()

Iterations

In [9]:
for step in range(5000):
  optimizer.minimize(mse_loss, var_list=[w, b])
  if step % 500 == 0:
    print(step, w.numpy(), b.numpy())

0 [0.04429672] [0.00099999]
500 [0.22157224] [0.187593]
1000 [0.21152155] [0.19377357]
1500 [0.20433392] [0.19765791]
2000 [0.20111077] [0.19939972]
2500 [0.20017707] [0.19990431]
3000 [0.20001546] [0.19999157]
3500 [0.2000013] [0.19999927]
4000 [0.20000103] [0.19999942]
4500 [0.20000082] [0.19999954]


**-------------------------------------------**

KERAS

Import libraries

In [10]:
from numpy import loadtxt
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense

In [11]:
dataset = loadtxt('pima-indians-diabetes.csv', delimiter = ',')
dataset

array([[  6.   , 148.   ,  72.   , ...,   0.627,  50.   ,   1.   ],
       [  1.   ,  85.   ,  66.   , ...,   0.351,  31.   ,   0.   ],
       [  8.   , 183.   ,  64.   , ...,   0.672,  32.   ,   1.   ],
       ...,
       [  5.   , 121.   ,  72.   , ...,   0.245,  30.   ,   0.   ],
       [  1.   , 126.   ,  60.   , ...,   0.349,  47.   ,   1.   ],
       [  1.   ,  93.   ,  70.   , ...,   0.315,  23.   ,   0.   ]])

In [12]:
x = dataset[:, 0:8]
print(type(x))
print(x.shape)

<class 'numpy.ndarray'>
(768, 8)


In [13]:
y = dataset[:, 8]
print(y)

[1. 0. 1. 0. 1. 0. 1. 0. 1. 1. 0. 1. 0. 1. 1. 1. 1. 1. 0. 1. 0. 0. 1. 1.
 1. 1. 1. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 1. 1. 1. 0. 0. 0. 1. 0. 1. 0. 0.
 1. 0. 0. 0. 0. 1. 0. 0. 1. 0. 0. 0. 0. 1. 0. 0. 1. 0. 1. 0. 0. 0. 1. 0.
 1. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 1. 0. 0. 0. 1. 0. 0. 0. 0. 1. 0. 0.
 0. 0. 0. 1. 1. 0. 0. 0. 0. 0. 0. 0. 0. 1. 1. 1. 0. 0. 1. 1. 1. 0. 0. 0.
 1. 0. 0. 0. 1. 1. 0. 0. 1. 1. 1. 1. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1.
 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 1. 1. 0. 0. 0. 1. 0. 0. 0. 0. 1. 1. 0. 0.
 0. 0. 1. 1. 0. 0. 0. 1. 0. 1. 0. 1. 0. 0. 0. 0. 0. 1. 1. 1. 1. 1. 0. 0.
 1. 1. 0. 1. 0. 1. 1. 1. 0. 0. 0. 0. 0. 0. 1. 1. 0. 1. 0. 0. 0. 1. 1. 1.
 1. 0. 1. 1. 1. 1. 0. 0. 0. 0. 0. 1. 0. 0. 1. 1. 0. 0. 0. 1. 1. 1. 1. 0.
 0. 0. 1. 1. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 1. 1. 0. 0. 0. 1. 0. 1. 0. 0.
 1. 0. 1. 0. 0. 1. 1. 0. 0. 0. 0. 0. 1. 0. 0. 0. 1. 0. 0. 1. 1. 0. 0. 1.
 0. 0. 0. 1. 1. 1. 0. 0. 1. 0. 1. 0. 1. 1. 0. 1. 0. 0. 1. 0. 1. 1. 0. 0.
 1. 0. 1. 0. 0. 1. 0. 1. 0. 1. 1. 1. 0. 0. 1. 0. 1.

In [14]:
model = Sequential()

In [15]:
model.add(Dense(12, input_shape=(8,), activation='relu'))

In [16]:
model.add(Dense(8, activation = 'relu'))

In [17]:
model.add(Dense(1, activation = 'sigmoid'))

In [18]:
model.compile(loss = 'binary_crossentropy', optimizer = 'adam', metrics = ['accuracy'])

In [19]:
model.fit(x, y, epochs = 150, batch_size = 10)

Epoch 1/150
77/77 [==============================] - 1s 2ms/step - loss: 29.9936 - accuracy: 0.6029
Epoch 2/150
77/77 [==============================] - 0s 2ms/step - loss: 5.6776 - accuracy: 0.4583
Epoch 3/150
77/77 [==============================] - 0s 2ms/step - loss: 2.2235 - accuracy: 0.5182
Epoch 4/150
77/77 [==============================] - 0s 2ms/step - loss: 1.4334 - accuracy: 0.5534
Epoch 5/150
77/77 [==============================] - 0s 2ms/step - loss: 1.1133 - accuracy: 0.5977
Epoch 6/150
77/77 [==============================] - 0s 2ms/step - loss: 0.9818 - accuracy: 0.6237
Epoch 7/150
77/77 [==============================] - 0s 2ms/step - loss: 0.9624 - accuracy: 0.6406
Epoch 8/150
77/77 [==============================] - 0s 2ms/step - loss: 0.8844 - accuracy: 0.6237
Epoch 9/150
77/77 [==============================] - 0s 2ms/step - loss: 0.8274 - accuracy: 0.6510
Epoch 10/150
77/77 [==============================] - 0s 2ms/step - loss: 0.8286 - accuracy: 0.6315
Epoch 11

In [20]:
model.evaluate(x, y)

24/24 [==============================] - 0s 2ms/step - loss: 0.5196 - accuracy: 0.7591


[0.5196417570114136, 0.7591145634651184]

**-------------------------------------------**

THEANO

Import libraries

In [21]:
import theano
from theano import *
import theano.tensor as T
import numpy as np
import pandas as pd
from theano import function

Scalar variable

In [22]:
v1 = T.dscalar()
v2 = T.scalar()

Subtraction

In [23]:
sres = v1 - v2

Add

In [24]:
ares = v1 + v2

Convert the results into functions

In [25]:
calcsres = theano.function([v1, v2], sres)
calcares = theano.function([v1, v2], ares)
calcares(12, 23)
calcsres(13, 12)
x = T.dmatrix('x')
y = T.dmatrix('y')

Addition

In [26]:
z = x + y
func = function([x, y], z)
m1 = [[1,2], [3,4]]
m2 = [[4,5], [6,7]]
func(m1, m2)

array([[ 5.,  7.],
       [ 9., 11.]])

**-------------------------------------------**

PYTORCH

Import libraries

In [27]:
import torch
import numpy as np

Using data

In [28]:
data = [[1,2], [3,4]]
x_data = torch.tensor(data)
print(type(x_data))

<class 'torch.Tensor'>


Using numpy arrays

In [29]:
np_array = np.array(data)
x_np = torch.from_numpy(np_array)
print(x_np)
print(type(x_np))

tensor([[1, 2],
        [3, 4]])
<class 'torch.Tensor'>


Using another tensor

In [30]:
x_ones = torch.ones_like(x_data)
print("One Tensor:\n", x_ones)
x_rand = torch.rand_like(x_data, dtype = torch.float)
print(x_rand)

One Tensor:
 tensor([[1, 1],
        [1, 1]])
tensor([[0.5230, 0.6781],
        [0.0150, 0.8114]])


More ways to create tensor

In [31]:
shape = (2, 3)
random_tensor = torch.rand(shape)
print(random_tensor)
print(type(random_tensor))
ones_tensor = torch.ones(shape)
print(ones_tensor)
print(type(ones_tensor))
zeros_tensor = torch.zeros(shape)
print(zeros_tensor)
print(type(zeros_tensor))
tensor = torch.rand(3, 4)
print(tensor)
tensor.shape
tensor.dtype
tensor.device

tensor([[0.1279, 0.4292, 0.5917],
        [0.0479, 0.5682, 0.9936]])
<class 'torch.Tensor'>
tensor([[1., 1., 1.],
        [1., 1., 1.]])
<class 'torch.Tensor'>
tensor([[0., 0., 0.],
        [0., 0., 0.]])
<class 'torch.Tensor'>
tensor([[0.0299, 0.7577, 0.5727, 0.4081],
        [0.9149, 0.8295, 0.2032, 0.0121],
        [0.6268, 0.5233, 0.9453, 0.2927]])


device(type='cpu')

Tensor Operations

In [32]:
if torch.cuda.is_available():
  tensor = tensor.to('cuda')
  print("Device tensor is stored in ", tensor.device)

Indexing, slicing

In [33]:
tensor = torch.ones(4, 4)
print("Tensor:\n", tensor)
tensor1 = torch.zeros(4, 4)
print("Tensor1:\n", tensor1)
tensor2 = torch.cat([tensor, tensor1])
print("Tensor2:\n", tensor2)

Tensor:
 tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])
Tensor1:
 tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])
Tensor2:
 tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])


Multiply Operation

In [34]:
tensor.mul(tensor1)
tensor * tensor1
tensor.T

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

Inplace change the original tensor

In [35]:
tensor.add_(3)
print(tensor)

tensor([[4., 4., 4., 4.],
        [4., 4., 4., 4.],
        [4., 4., 4., 4.],
        [4., 4., 4., 4.]])


From tensor to numpy

In [36]:
t = torch.ones(5)
print(t)
n = t.numpy()
print(n)
print(type(n))

tensor([1., 1., 1., 1., 1.])
[1. 1. 1. 1. 1.]
<class 'numpy.ndarray'>
